version: "3.3"
volumes:
  shared-workspace:
    name: "hdfs"
    driver: local
  postgres:
    name: "postgres"
services:
  spark-master:
    image: spark-cluster:latest
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./logs/master:/opt/spark/logs
       - shared-workspace:/opt/workspace
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: spark-cluster:latest
    container_name: spark-worker-a
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./logs/worker-a:/opt/spark/logs
       - shared-workspace:/opt/workspace
  spark-worker-b:
    image: spark-cluster:latest
    container_name: spark-worker-b
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./logs/worker-b:/opt/spark/logs
        - shared-workspace:/opt/workspace
  spark-worker-c:
    image: spark-cluster:latest
    container_name: spark-worker-c
    ports:
      - "9093:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-c
    volumes:
        - ./logs/worker-c:/opt/spark/logs
        - shared-workspace:/opt/workspace
  spark-worker-d:
    image: spark-cluster:latest
    container_name: spark-worker-d
    ports:
      - "9094:8080"
      - "7003:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-d
    volumes:
        - ./logs/worker-d:/opt/spark/logs
        - shared-workspace:/opt/workspace
  jupyterlab:
    image: spark-cluster:latest
    container_name: jupyterlab
    environment:
        - SPARK_WORKLOAD=jupyter
    ports: 
        - "8888:8888"
    volumes:
        - ./src:/opt/workspace/src
        - shared-workspace:/opt/workspace
  demo-database:
    image: postgres:15.1-alpine
    container_name: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=spark
    volumes:
      - postgres:/var/lib/postgresql/data